approve_by_comment: true
approve_regex: '^:\+1:'
reject_regex: '^(Rejected|:-1:)'
reject_value: -1
reset_on_push: false
reviewers:
    required: 1
    members:
        - nicoschmitt
    teams:
        - maintainers

